var c;c||(c=typeof Module !== 'undefined' ? Module : {});var k={},n;for(n in c)c.hasOwnProperty(n)&&(k[n]=c[n]);c.arguments=[];c.thisProgram="./this.program";c.quit=function(a,b){throw b;};c.preRun=[];c.postRun=[];var p=!1,t=!1,aa=!1,ba=!1;p="object"===typeof window;t="function"===typeof importScripts;aa="object"===typeof process&&"function"===typeof require&&!p&&!t;ba=!p&&!aa&&!t;var v="";function ca(a){return c.locateFile?c.locateFile(a,v):v+a}
if(aa){v=__dirname+"/";var da,ea;c.read=function(a,b){da||(da=require("fs"));ea||(ea=require("path"));a=ea.normalize(a);a=da.readFileSync(a);return b?a:a.toString()};c.readBinary=function(a){a=c.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(c.thisProgram=process.argv[1].replace(/\\/g,"/"));c.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=c);process.on("uncaughtException",function(a){if(!(a instanceof w))throw a;});process.on("unhandledRejection",
x);c.quit=function(a){process.exit(a)};c.inspect=function(){return"[Emscripten Module object]"}}else if(ba)"undefined"!=typeof read&&(c.read=function(a){return read(a)}),c.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?c.arguments=scriptArgs:"undefined"!=typeof arguments&&(c.arguments=arguments),"function"===typeof quit&&(c.quit=function(a){quit(a)});else if(p||t)t?
v=self.location.href:document.currentScript&&(v=document.currentScript.src),v=0!==v.indexOf("blob:")?v.substr(0,v.lastIndexOf("/")+1):"",c.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},t&&(c.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),c.readAsync=function(a,b,d){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==
e.status||0==e.status&&e.response?b(e.response):d()};e.onerror=d;e.send(null)},c.setWindowTitle=function(a){document.title=a};var fa=c.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),y=c.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||fa);for(n in k)k.hasOwnProperty(n)&&(c[n]=k[n]);k=void 0;function ha(a){var b;b||(b=16);return Math.ceil(a/b)*b}
function ia(a){ja||(ja={});ja[a]||(ja[a]=1,y(a))}var ja,ka={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},z=!1;function assert(a,b){a||x("Assertion failed: "+b)}function A(a,b){if(0===b||!a)return"";for(var d=0,e,f=0;;){e=B[a+f>>0];d|=e;if(0==e&&!b)break;f++;if(b&&f==b)break}b||(b=f);e="";if(128>d){for(;0<b;)d=String.fromCharCode.apply(String,B.subarray(a,a+Math.min(b,1024))),e=e?e+d:d,a+=1024,b-=1024;return e}return la(B,a)}
var ma="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function la(a,b){for(var d=b;a[d];)++d;if(16<d-b&&a.subarray&&ma)return ma.decode(a.subarray(b,d));for(d="";;){var e=a[b++];if(!e)return d;if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;if(224==(e&240))e=(e&15)<<12|f<<6|g;else{var h=a[b++]&63;if(240==(e&248))e=(e&7)<<18|f<<12|g<<6|h;else{var m=a[b++]&63;if(248==(e&252))e=(e&3)<<24|f<<18|g<<12|h<<6|m;else{var l=a[b++]&63;e=(e&1)<<30|f<<24|g<<18|h<<12|m<<6|l}}}65536>e?d+=String.fromCharCode(e):(e-=
65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}}
function na(a,b,d,e){if(!(0<e))return 0;var f=d;e=d+e-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(d>=e)break;b[d++]=h}else{if(2047>=h){if(d+1>=e)break;b[d++]=192|h>>6}else{if(65535>=h){if(d+2>=e)break;b[d++]=224|h>>12}else{if(2097151>=h){if(d+3>=e)break;b[d++]=240|h>>18}else{if(67108863>=h){if(d+4>=e)break;b[d++]=248|h>>24}else{if(d+5>=e)break;b[d++]=252|h>>30;b[d++]=128|h>>24&63}b[d++]=128|h>>18&63}b[d++]=
128|h>>12&63}b[d++]=128|h>>6&63}b[d++]=128|h&63}}b[d]=0;return d-f}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function oa(a){for(var b=0,d=0;d<a.length;++d){var e=a.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++d)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:2097151>=e?b+4:67108863>=e?b+5:b+6}b+=1;d=pa(b);na(a,qa,d,b);return d}function ra(a,b){0<a%b&&(a+=b-a%b);return a}var buffer,qa,B,C,sa,D;
function ta(){c.HEAP8=qa=new Int8Array(buffer);c.HEAP16=new Int16Array(buffer);c.HEAP32=C=new Int32Array(buffer);c.HEAPU8=B=new Uint8Array(buffer);c.HEAPU16=new Uint16Array(buffer);c.HEAPU32=sa=new Uint32Array(buffer);c.HEAPF32=D=new Float32Array(buffer);c.HEAPF64=new Float64Array(buffer)}var ua,E,va,wa,xa,ya,F;ua=E=va=wa=xa=ya=F=0;c.reallocBuffer||(c.reallocBuffer=function(a){try{var b=qa;var d=new ArrayBuffer(a);(new Int8Array(d)).set(b)}catch(e){return!1}return za(d)?d:!1});var Aa;
try{Aa=Function.prototype.call.bind(Object.getOwnPropertyDescriptor(ArrayBuffer.prototype,"byteLength").get),Aa(new ArrayBuffer(4))}catch(a){Aa=function(b){return b.byteLength}}var Ba=c.TOTAL_STACK||5242880,G=c.TOTAL_MEMORY||16777216;G<Ba&&y("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+G+"! (TOTAL_STACK="+Ba+")");
c.buffer?buffer=c.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(c.wasmMemory=new WebAssembly.Memory({initial:G/65536}),buffer=c.wasmMemory.buffer):buffer=new ArrayBuffer(G),c.buffer=buffer);ta();function H(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var d=b.s;"number"===typeof d?void 0===b.c?c.dynCall_v(d):c.dynCall_vi(d,b.c):d(void 0===b.c?null:b.c)}}}var Ca=[],Da=[],Ea=[],Fa=[],Ga=[],Ha=!1;
function Ia(){var a=c.preRun.shift();Ca.unshift(a)}var I=0,Ja=null,J=null;c.preloadedImages={};c.preloadedAudios={};function Ka(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(c.wasmBinary)return new Uint8Array(c.wasmBinary);if(c.readBinary)return c.readBinary(f);throw"both async and sync fetching of the wasm failed";}catch(r){x(r)}}function b(){return c.wasmBinary||!p&&!t||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+"'";return a.arrayBuffer()}).catch(function(){return a()})}function d(a){function d(a){m=a.exports;if(m.memory){a=
m.memory;var b=c.buffer;a.byteLength<b.byteLength&&y("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);c.buffer=buffer=a;ta()}c.asm=m;c.usingWasm=!0;I--;c.monitorRunDependencies&&c.monitorRunDependencies(I);0==I&&(null!==Ja&&(clearInterval(Ja),Ja=null),J&&(a=J,J=null,a()))}function e(a){d(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,h)}).then(a,function(a){y("failed to asynchronously prepare wasm: "+
a);x(a)})}if("object"!==typeof WebAssembly)return y("no native wasm support detected"),!1;if(!(c.wasmMemory instanceof WebAssembly.Memory))return y("no native wasm Memory in use"),!1;a.memory=c.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;I++;c.monitorRunDependencies&&c.monitorRunDependencies(I);if(c.instantiateWasm)try{return c.instantiateWasm(h,d)}catch(Ab){return y("Module.instantiateWasm callback failed with error: "+Ab),!1}c.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||
Ka(f)||"function"!==typeof fetch?g(e):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),h).then(e,function(a){y("wasm streaming compile failed: "+a);y("falling back to ArrayBuffer instantiation");g(e)});return{}}var e="draw_geometry.wast",f="draw_geometry.wasm",g="draw_geometry.temp.asm.js";Ka(e)||(e=ca(e));Ka(f)||(f=ca(f));Ka(g)||(g=ca(g));var h={global:null,env:null,asm2wasm:ka,parent:c},m=null;c.asmPreload=c.asm;var l=c.reallocBuffer;c.reallocBuffer=function(a){if("asmjs"===
q)var b=l(a);else a:{a=ra(a,c.usingWasm?65536:16777216);var d=c.buffer.byteLength;if(c.usingWasm)try{b=-1!==c.wasmMemory.grow((a-d)/65536)?c.buffer=c.wasmMemory.buffer:null;break a}catch(Nb){b=null;break a}b=void 0}return b};var q="";c.asm=function(a,b){if(!b.table){a=c.wasmTableSize;void 0===a&&(a=1024);var e=c.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==e?new WebAssembly.Table({initial:a,maximum:e,element:"anyfunc"}):new WebAssembly.Table({initial:a,
element:"anyfunc"}):Array(a);c.wasmTable=b.table}b.memoryBase||(b.memoryBase=c.STATIC_BASE);b.tableBase||(b.tableBase=0);b=d(b);assert(b,"no binaryen method succeeded.");return b}})();ua=1024;E=ua+7616;Da.push();c.STATIC_BASE=ua;c.STATIC_BUMP=7616;E+=16;var La=[null,[],[]],K=0;function L(){K+=4;return C[K-4>>2]}var Ma={};function M(){x()}var Na=0;
function Oa(a){return a?("number"==typeof a&&(a=A(a)),"#window"==a?window:"#document"==a?document:"#screen"==a?window.screen:"#canvas"==a?c.canvas:"string"==typeof a?document.getElementById(a):a):window}var N=null,O="",P=0,Q=null,Pa=0,Qa=0,Ra=0,Sa=0,Ta=[],Ua={},Va,Wa,R,Xa=!1,Ya=!1,Za=[];
function $a(){function a(){Ya=document.pointerLockElement===c.canvas||document.mozPointerLockElement===c.canvas||document.webkitPointerLockElement===c.canvas||document.msPointerLockElement===c.canvas}c.preloadPlugins||(c.preloadPlugins=[]);if(!ab){ab=!0;try{S=!0}catch(d){S=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}bb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:S?null:console.log("warning: no BlobBuilder");
cb="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;c.j||"undefined"!==typeof cb||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),c.j=!0);c.preloadPlugins.push({canHandle:function(a){return!c.j&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,b,f,g){var d=null;if(S)try{d=new Blob([a],{type:db(b)}),d.size!==a.length&&(d=new Blob([(new Uint8Array(a)).buffer],{type:db(b)}))}catch(q){ia("Blob constructor present but fails: "+
q+"; falling back to blob builder")}d||(d=new bb,d.append((new Uint8Array(a)).buffer),d=d.getBlob());var e=cb.createObjectURL(d),l=new Image;l.onload=function(){assert(l.complete,"Image "+b+" could not be decoded");var d=document.createElement("canvas");d.width=l.width;d.height=l.height;d.getContext("2d").drawImage(l,0,0);c.preloadedImages[b]=d;cb.revokeObjectURL(e);f&&f(a)};l.onerror=function(){console.log("Image "+e+" could not be decoded");g&&g()};l.src=e}});c.preloadPlugins.push({canHandle:function(a){return!c.L&&
a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,f,g){function d(d){l||(l=!0,c.preloadedAudios[b]=d,f&&f(a))}function e(){l||(l=!0,c.preloadedAudios[b]=new Audio,g&&g())}var l=!1;if(S){try{var q=new Blob([a],{type:db(b)})}catch(u){return e()}q=cb.createObjectURL(q);var r=new Audio;r.addEventListener("canplaythrough",function(){d(r)},!1);r.onerror=function(){if(!l){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var e="",f=0,h=0,
g=0;g<a.length;g++)for(f=f<<8|a[g],h+=8;6<=h;){var m=f>>h-6&63;h-=6;e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[m]}2==h?(e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&3)<<4],e+="=="):4==h&&(e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&15)<<2],e+="=");r.src="data:audio/x-"+b.substr(-3)+";base64,"+e;d(r)}};r.src=q;eb(function(){d(r)})}else return e()}});var b=c.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),c.elementPointerLock&&
b.addEventListener("click",function(a){!Ya&&c.canvas.requestPointerLock&&(c.canvas.requestPointerLock(),a.preventDefault())},!1))}}
function fb(a,b,d,e){if(b&&c.f&&a==c.canvas)return c.f;if(b){var f={antialias:!1,alpha:!1};if(e)for(var g in e)f[g]=e[g];if(f=gb(a,f))var h=hb[f].GLctx}else h=a.getContext("2d");if(!h)return null;d&&(b||assert("undefined"===typeof GLctx,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),c.f=h,b&&ib(f),c.M=b,Za.forEach(function(a){a()}),$a());return h}var jb=!1,kb=void 0,T=void 0;
function lb(a,b,d){function e(){Xa=!1;var a=f.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a?(f.exitFullscreen=document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){},f.exitFullscreen=f.exitFullscreen.bind(document),kb&&f.requestPointerLock(),Xa=!0,T?("undefined"!=typeof SDL&&
(C[SDL.screen>>2]=sa[SDL.screen>>2]|8388608),mb(c.canvas),nb()):mb(f)):(a.parentNode.insertBefore(f,a),a.parentNode.removeChild(a),T?("undefined"!=typeof SDL&&(C[SDL.screen>>2]=sa[SDL.screen>>2]&-8388609),mb(c.canvas),nb()):mb(f));if(c.onFullScreen)c.onFullScreen(Xa);if(c.onFullscreen)c.onFullscreen(Xa)}kb=a;T=b;ob=d;"undefined"===typeof kb&&(kb=!0);"undefined"===typeof T&&(T=!1);"undefined"===typeof ob&&(ob=null);var f=c.canvas;jb||(jb=!0,document.addEventListener("fullscreenchange",e,!1),document.addEventListener("mozfullscreenchange",
e,!1),document.addEventListener("webkitfullscreenchange",e,!1),document.addEventListener("MSFullscreenChange",e,!1));var g=document.createElement("div");f.parentNode.insertBefore(g,f);g.appendChild(f);g.requestFullscreen=g.requestFullscreen||g.mozRequestFullScreen||g.msRequestFullscreen||(g.webkitRequestFullscreen?function(){g.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(g.webkitRequestFullScreen?function(){g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);d?g.requestFullscreen({N:d}):
g.requestFullscreen()}function pb(a,b,d){y("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");pb=function(a,b,d){return lb(a,b,d)};return lb(a,b,d)}var qb=0;function rb(a){var b=Date.now();if(0===qb)qb=b+1E3/60;else for(;b+2>=qb;)qb+=1E3/60;setTimeout(a,Math.max(qb-b,0))}
function sb(a){"undefined"===typeof window?rb(a):(window.requestAnimationFrame||(window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||window.oRequestAnimationFrame||rb),window.requestAnimationFrame(a))}function eb(a){c.noExitRuntime=!0;setTimeout(function(){z||a()},1E4)}
function db(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var tb=[];function nb(){var a=c.canvas;tb.forEach(function(b){b(a.width,a.height)})}
function mb(a,b,d){b&&d?(a.C=b,a.w=d):(b=a.C,d=a.w);var e=b,f=d;c.forcedAspectRatio&&0<c.forcedAspectRatio&&(e/f<c.forcedAspectRatio?e=Math.round(f*c.forcedAspectRatio):f=Math.round(e/c.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/e,screen.height/f);e=Math.round(e*g);f=Math.round(f*g)}T?
(a.width!=e&&(a.width=e),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=d&&(a.height=d),"undefined"!=typeof a.style&&(e!=b||f!=d?(a.style.setProperty("width",e+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var ab,S,bb,cb,ob;
function ub(a,b){Qa=a;Ra=b;if(Q)if(0==a)N=function(){var a=Math.max(0,Wa+b-M())|0;setTimeout(R,a)},O="timeout";else if(1==a)N=function(){sb(R)},O="rAF";else if(2==a){if("undefined"===typeof setImmediate){var d=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),d.shift()()},!0);setImmediate=function(a){d.push(a);t?(void 0===c.setImmediates&&(c.setImmediates=[]),c.setImmediates.push(a),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}N=function(){setImmediate(R)};O="immediate"}}
function vb(a,b,d,e,f){c.noExitRuntime=!0;assert(!Q,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Q=a;Pa=e;var g="undefined"!==typeof e?function(){c.dynCall_vi(a,e)}:function(){c.dynCall_v(a)};var h=P;R=function(){if(!z)if(0<Ta.length){var a=Date.now(),b=Ta.shift();b.s(b.c);if(Va){var d=Va,e=0==d%1?d-1:Math.floor(d);Va=b.G?e:(8*d+(e+.5))/9}console.log('main loop blocker "'+
b.name+'" took '+(Date.now()-a)+" ms");c.setStatus&&(a=c.statusMessage||"Please wait...",b=Va,d=Ua.I,b?b<d?c.setStatus(a+" ("+(d-b)+"/"+d+")"):c.setStatus(a):c.setStatus(""));h<P||setTimeout(R,0)}else if(!(h<P))if(Sa=Sa+1|0,1==Qa&&1<Ra&&0!=Sa%Ra)N();else{0==Qa&&(Wa=M());"timeout"===O&&c.f&&(y("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),
O="");a:if(!(z||c.preMainLoop&&!1===c.preMainLoop())){try{g()}catch(u){if(u instanceof w)break a;u&&"object"===typeof u&&u.stack&&y("exception thrown: "+[u,u.stack]);throw u;}c.postMainLoop&&c.postMainLoop()}h<P||("object"===typeof SDL&&SDL.audio&&SDL.audio.B&&SDL.audio.B(),N())}};f||(b&&0<b?ub(0,1E3/b):ub(1,1),N());if(d)throw"SimulateInfiniteLoop";}var wb=1,xb=0,yb=[],U=[],V=[],W=[],hb=[],zb=null,Bb={},Cb={},Db=[];function X(a){xb||(xb=a)}
function Y(a){for(var b=wb++,d=a.length;d<b;d++)a[d]=null;return b}var Eb=null,Fb=[0];
function gb(a,b){function d(){}"undefined"===typeof b.majorVersion&&"undefined"===typeof b.minorVersion&&(b.majorVersion=1,b.minorVersion=0);try{a.addEventListener("webglcontextcreationerror",d,!1);try{if(1==b.majorVersion&&0==b.minorVersion)var e=a.getContext("webgl",b)||a.getContext("experimental-webgl",b);else if(2==b.majorVersion&&0==b.minorVersion)e=a.getContext("webgl2",b);else throw"Unsupported WebGL context version "+majorVersion+"."+minorVersion+"!";}finally{a.removeEventListener("webglcontextcreationerror",
d,!1)}if(!e)throw":(";}catch(f){return 0}return e?Gb(e,b):0}function Gb(a,b){var d=Y(hb),e={handle:d,attributes:b,version:b.majorVersion,GLctx:a};a.canvas&&(a.canvas.F=e);hb[d]=e;("undefined"===typeof b.enableExtensionsByDefault||b.enableExtensionsByDefault)&&Hb(e);return d}function ib(a){a=hb[a];if(!a)return!1;GLctx=c.f=a.GLctx;zb=a;return!0}
function Hb(a){a||(a=zb);if(!a.A){a.A=!0;var b=a.GLctx;if(2>a.version){var d=b.getExtension("ANGLE_instanced_arrays");d&&(b.vertexAttribDivisor=function(a,b){d.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,e,f){d.drawArraysInstancedANGLE(a,b,e,f)},b.drawElementsInstanced=function(a,b,e,f,g){d.drawElementsInstancedANGLE(a,b,e,f,g)});var e=b.getExtension("OES_vertex_array_object");e&&(b.createVertexArray=function(){return e.createVertexArrayOES()},b.deleteVertexArray=function(a){e.deleteVertexArrayOES(a)},
b.bindVertexArray=function(a){e.bindVertexArrayOES(a)},b.isVertexArray=function(a){return e.isVertexArrayOES(a)});var f=b.getExtension("WEBGL_draw_buffers");f&&(b.drawBuffers=function(a,b){f.drawBuffersWEBGL(a,b)})}b.H=b.getExtension("EXT_disjoint_timer_query");var g="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=g.indexOf(a)&&b.getExtension(a)})}}function _glDrawArrays(a,b,d){GLctx.drawArrays(a,b,d)}
aa?M=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?M=dateNow:"object"===typeof self&&self.performance&&"function"===typeof self.performance.now?M=function(){return self.performance.now()}:"object"===typeof performance&&"function"===typeof performance.now?M=function(){return performance.now()}:M=Date.now;
(function(){if("undefined"!==typeof window){window.addEventListener("gamepadconnected",function(){++Na});window.addEventListener("gamepaddisconnected",function(){--Na});var a=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null;a&&(Na=a.length)}})();c.requestFullScreen=function(a,b,d){y("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");c.requestFullScreen=c.requestFullscreen;pb(a,b,d)};
c.requestFullscreen=function(a,b,d){lb(a,b,d)};c.requestAnimationFrame=function(a){sb(a)};c.setCanvasSize=function(a,b,d){mb(c.canvas,a,b);d||nb()};c.pauseMainLoop=function(){N=null;P++};c.resumeMainLoop=function(){P++;var a=Qa,b=Ra,d=Q;Q=null;vb(d,0,!1,Pa,!0);ub(a,b);N()};c.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};c.createContext=function(a,b,d,e){return fb(a,b,d,e)};var GLctx;Eb=new Float32Array(256);
for(var Z=0;256>Z;Z++)Fb[Z]=Eb.subarray(0,Z+1);for(Z=0;32>Z;Z++)Db.push(Array(Z));var Ib=E;E=E+4+15&-16;F=Ib;va=wa=ha(E);xa=va+Ba;ya=ha(xa);C[F>>2]=ya;c.wasmTableSize=8;c.wasmMaxTableSize=8;c.m={};
c.o={abort:x,enlargeMemory:function(){var a=c.usingWasm?65536:16777216,b=2147483648-a;if(C[F>>2]>b)return!1;var d=G;for(G=Math.max(G,16777216);G<C[F>>2];)536870912>=G?G=ra(2*G,a):G=Math.min(ra((3*G+2147483648)/4,a),b);a=c.reallocBuffer(G);if(!a||a.byteLength!=G)return G=d,!1;c.buffer=buffer=a;ta();return!0},getTotalMemory:function(){return G},abortOnCannotGrowMemory:function(){x("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+G+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},
___setErrNo:function(a){c.___errno_location&&(C[c.___errno_location()>>2]=a);return a},___syscall140:function(a,b){K=b;try{var d=Ma.u();L();var e=L(),f=L(),g=L();FS.K(d,e,g);C[f>>2]=d.position;d.v&&0===e&&0===g&&(d.v=null);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof FS.h||x(h),-h.i}},___syscall146:function(a,b){K=b;try{var d=L(),e=L(),f=L();for(b=a=0;b<f;b++){for(var g=C[e+8*b>>2],h=C[e+(8*b+4)>>2],m=0;m<h;m++){var l=d,q=B[g+m],r=La[l];assert(r);0===q||10===q?((1===l?fa:y)(la(r,
0)),r.length=0):r.push(q)}a+=h}return a}catch(u){return"undefined"!==typeof FS&&u instanceof FS.h||x(u),-u.i}},___syscall54:function(a,b){K=b;return 0},___syscall6:function(a,b){K=b;try{var d=Ma.u();FS.close(d);return 0}catch(e){return"undefined"!==typeof FS&&e instanceof FS.h||x(e),-e.i}},_emscripten_get_now:M,_emscripten_memcpy_big:function(a,b,d){B.set(B.subarray(b,b+d),a);return a},_emscripten_set_canvas_element_size:function(a,b,d){a=a?Oa(a):c.canvas;if(!a)return-4;a.width=b;a.height=d;return 0},
_emscripten_set_main_loop:vb,_emscripten_webgl_create_context:function(a,b){var d={};d.alpha=!!C[b>>2];d.depth=!!C[b+4>>2];d.stencil=!!C[b+8>>2];d.antialias=!!C[b+12>>2];d.premultipliedAlpha=!!C[b+16>>2];d.preserveDrawingBuffer=!!C[b+20>>2];d.preferLowPowerToHighPerformance=!!C[b+24>>2];d.failIfMajorPerformanceCaveat=!!C[b+28>>2];d.majorVersion=C[b+32>>2];d.minorVersion=C[b+36>>2];d.enableExtensionsByDefault=C[b+40>>2];d.explicitSwapControl=C[b+44>>2];d.renderViaOffscreenBackBuffer=C[b+48>>2];a=(a=
A(a))&&"#canvas"!==a||!c.canvas?Bb[a]||Oa(a):c.canvas.id?Bb[c.canvas.id]||Oa(c.canvas.id):c.canvas;return!a||d.explicitSwapControl?0:gb(a,d)},_emscripten_webgl_init_context_attributes:function(a){C[a>>2]=1;C[a+4>>2]=1;C[a+8>>2]=0;C[a+12>>2]=1;C[a+16>>2]=1;C[a+20>>2]=0;C[a+24>>2]=0;C[a+28>>2]=0;C[a+32>>2]=1;C[a+36>>2]=0;C[a+40>>2]=1;C[a+44>>2]=0;C[a+48>>2]=0},_emscripten_webgl_make_context_current:function(a){return ib(a)?0:-5},_glAttachShader:function(a,b){GLctx.attachShader(U[a],W[b])},_glBindAttribLocation:function(a,
b,d){d=A(d);GLctx.bindAttribLocation(U[a],b,d)},_glBindBuffer:function(a,b){GLctx.bindBuffer(a,b?yb[b]:null)},_glBlendFunc:function(a,b){GLctx.blendFunc(a,b)},_glBufferData:function(a,b,d,e){d?GLctx.bufferData(a,B.subarray(d,d+b),e):GLctx.bufferData(a,b,e)},_glClear:function(a){GLctx.clear(a)},_glClearColor:function(a,b,d,e){GLctx.clearColor(a,b,d,e)},_glCompileShader:function(a){GLctx.compileShader(W[a])},_glCreateProgram:function(){var a=Y(U),b=GLctx.createProgram();b.name=a;U[a]=b;return a},_glCreateShader:function(a){var b=
Y(W);W[b]=GLctx.createShader(a);return b},_glDeleteShader:function(a){if(a){var b=W[a];b?(GLctx.deleteShader(b),W[a]=null):X(1281)}},_glDetachShader:function(a,b){GLctx.detachShader(U[a],W[b])},_glDrawArrays:_glDrawArrays,_glEnable:function(a){GLctx.enable(a)},_glEnableVertexAttribArray:function(a){GLctx.enableVertexAttribArray(a)},_glGenBuffers:function(a,b){for(var d=0;d<a;d++){var e=GLctx.createBuffer();if(!e){for(X(1282);d<a;)C[b+4*d++>>2]=0;break}var f=Y(yb);e.name=f;yb[f]=e;C[b+4*d>>2]=f}},
_glGetProgramiv:function(a,b,d){if(d)if(a>=wb)X(1281);else{var e=Cb[a];if(e)if(35716==b)a=GLctx.getProgramInfoLog(U[a]),null===a&&(a="(unknown error)"),C[d>>2]=a.length+1;else if(35719==b)C[d>>2]=e.g;else if(35722==b){if(-1==e.a){a=U[a];var f=GLctx.getProgramParameter(a,GLctx.ACTIVE_ATTRIBUTES);for(b=e.a=0;b<f;++b)e.a=Math.max(e.a,GLctx.getActiveAttrib(a,b).name.length+1)}C[d>>2]=e.a}else if(35381==b){if(-1==e.b)for(a=U[a],f=GLctx.getProgramParameter(a,GLctx.D),b=e.b=0;b<f;++b){var g=GLctx.J(a,b);
e.b=Math.max(e.b,g.length+1)}C[d>>2]=e.b}else C[d>>2]=GLctx.getProgramParameter(U[a],b);else X(1282)}else X(1281)},_glGetShaderInfoLog:function(a,b,d,e){a=GLctx.getShaderInfoLog(W[a]);null===a&&(a="(unknown error)");0<b&&e?(b=na(a,B,e,b),d&&(C[d>>2]=b)):d&&(C[d>>2]=0)},_glGetShaderiv:function(a,b,d){d?35716==b?(a=GLctx.getShaderInfoLog(W[a]),null===a&&(a="(unknown error)"),C[d>>2]=a.length+1):35720==b?(a=GLctx.getShaderSource(W[a]),C[d>>2]=null===a||0==a.length?0:a.length+1):C[d>>2]=GLctx.getShaderParameter(W[a],
b):X(1281)},_glGetUniformLocation:function(a,b){b=A(b);var d=0;if(-1!==b.indexOf("]",b.length-1)){var e=b.lastIndexOf("["),f=b.slice(e+1,-1);if(0<f.length&&(d=parseInt(f),0>d))return-1;b=b.slice(0,e)}a=Cb[a];return a?(b=a.l[b])&&d<b[0]?b[1]+d:-1:-1},_glLinkProgram:function(a){GLctx.linkProgram(U[a]);Cb[a]=null;var b=U[a];Cb[a]={l:{},g:0,a:-1,b:-1};a=Cb[a];for(var d=a.l,e=GLctx.getProgramParameter(b,GLctx.ACTIVE_UNIFORMS),f=0;f<e;++f){var g=GLctx.getActiveUniform(b,f),h=g.name;a.g=Math.max(a.g,h.length+
1);-1!==h.indexOf("]",h.length-1)&&(h=h.slice(0,h.lastIndexOf("[")));var m=GLctx.getUniformLocation(b,h);if(null!=m){var l=Y(V);d[h]=[g.size,l];V[l]=m;for(var q=1;q<g.size;++q)m=GLctx.getUniformLocation(b,h+"["+q+"]"),l=Y(V),V[l]=m}}},_glShaderSource:function(a,b,d,e){for(var f="",g=0;g<b;++g){if(e){var h=C[e+4*g>>2];h=0>h?A(C[d+4*g>>2]):A(C[d+4*g>>2],h)}else h=A(C[d+4*g>>2]);f+=h}GLctx.shaderSource(W[a],f)},_glUniform1f:function(a,b){GLctx.uniform1f(V[a],b)},_glUniform4fv:function(a,b,d){if(256>=
4*b){var e=Fb[4*b-1];for(var f=0;f<4*b;f+=4)e[f]=D[d+4*f>>2],e[f+1]=D[d+(4*f+4)>>2],e[f+2]=D[d+(4*f+8)>>2],e[f+3]=D[d+(4*f+12)>>2]}else e=D.subarray(d>>2,d+16*b>>2);GLctx.uniform4fv(V[a],e)},_glUseProgram:function(a){GLctx.useProgram(a?U[a]:null)},_glValidateProgram:function(a){GLctx.validateProgram(U[a])},_glVertexAttribPointer:function(a,b,d,e,f,g){GLctx.vertexAttribPointer(a,b,d,!!e,f,g)},DYNAMICTOP_PTR:F,STACKTOP:wa};var Jb=c.asm(c.m,c.o,buffer);c.asm=Jb;
c.___errno_location=function(){return c.asm.___errno_location.apply(null,arguments)};var za=c._emscripten_replace_memory=function(){return c.asm._emscripten_replace_memory.apply(null,arguments)};c._main=function(){return c.asm._main.apply(null,arguments)};c._malloc=function(){return c.asm._malloc.apply(null,arguments)};var pa=c.stackAlloc=function(){return c.asm.stackAlloc.apply(null,arguments)};c.dynCall_iiii=function(){return c.asm.dynCall_iiii.apply(null,arguments)};
c.dynCall_v=function(){return c.asm.dynCall_v.apply(null,arguments)};c.asm=Jb;function w(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}w.prototype=Error();w.prototype.constructor=w;J=function Kb(){c.calledRun||Lb();c.calledRun||(J=Kb)};
c.callMain=function(a){a=a||[];Ha||(Ha=!0,H(Da));var b=a.length+1,d=pa(4*(b+1));C[d>>2]=oa(c.thisProgram);for(var e=1;e<b;e++)C[(d>>2)+e]=oa(a[e-1]);C[(d>>2)+b]=0;try{var f=c._main(b,d,0);if(!c.noExitRuntime||0!==f){if(!c.noExitRuntime&&(z=!0,wa=void 0,H(Fa),c.onExit))c.onExit(f);c.quit(f,new w(f))}}catch(g){g instanceof w||("SimulateInfiniteLoop"==g?c.noExitRuntime=!0:((a=g)&&"object"===typeof g&&g.stack&&(a=[g,g.stack]),y("exception thrown: "+a),c.quit(1,g)))}finally{}};
function Lb(a){function b(){if(!c.calledRun&&(c.calledRun=!0,!z)){Ha||(Ha=!0,H(Da));H(Ea);if(c.onRuntimeInitialized)c.onRuntimeInitialized();c._main&&Mb&&c.callMain(a);if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var b=c.postRun.shift();Ga.unshift(b)}H(Ga)}}a=a||c.arguments;if(!(0<I)){if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)Ia();H(Ca);0<I||c.calledRun||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},
1);b()},1)):b())}}c.run=Lb;function x(a){if(c.onAbort)c.onAbort(a);void 0!==a?(fa(a),y(a),a=JSON.stringify(a)):a="";z=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}c.abort=x;if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();var Mb=!0;c.noInitialRun&&(Mb=!1);c.noExitRuntime=!0;Lb();
