var d;d||(d=typeof Module !== 'undefined' ? Module : {});var k={},n;for(n in d)d.hasOwnProperty(n)&&(k[n]=d[n]);d.arguments=[];d.thisProgram="./this.program";d.quit=function(a,b){throw b;};d.preRun=[];d.postRun=[];var p=!1,r=!1,aa=!1,ba=!1;p="object"===typeof window;r="function"===typeof importScripts;aa="object"===typeof process&&"function"===typeof require&&!p&&!r;ba=!p&&!aa&&!r;var v="";function ca(a){return d.locateFile?d.locateFile(a,v):v+a}
if(aa){v=__dirname+"/";var da,ea;d.read=function(a,b){da||(da=require("fs"));ea||(ea=require("path"));a=ea.normalize(a);a=da.readFileSync(a);return b?a:a.toString()};d.readBinary=function(a){a=d.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(d.thisProgram=process.argv[1].replace(/\\/g,"/"));d.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=d);process.on("uncaughtException",function(a){if(!(a instanceof w))throw a;});process.on("unhandledRejection",
x);d.quit=function(a){process.exit(a)};d.inspect=function(){return"[Emscripten Module object]"}}else if(ba)"undefined"!=typeof read&&(d.read=function(a){return read(a)}),d.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?d.arguments=scriptArgs:"undefined"!=typeof arguments&&(d.arguments=arguments),"function"===typeof quit&&(d.quit=function(a){quit(a)});else if(p||r)r?
v=self.location.href:document.currentScript&&(v=document.currentScript.src),v=0!==v.indexOf("blob:")?v.substr(0,v.lastIndexOf("/")+1):"",d.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},r&&(d.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),d.readAsync=function(a,b,c){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==
e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)},d.setWindowTitle=function(a){document.title=a};var fa=d.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),y=d.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||fa);for(n in k)k.hasOwnProperty(n)&&(d[n]=k[n]);k=void 0;function ha(a){var b;b||(b=16);return Math.ceil(a/b)*b}
function ia(a){ja||(ja={});ja[a]||(ja[a]=1,y(a))}var ja,ka={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},z=!1;function assert(a,b){a||x("Assertion failed: "+b)}function A(a,b){if(0===b||!a)return"";for(var c=0,e,f=0;;){e=B[a+f>>0];c|=e;if(0==e&&!b)break;f++;if(b&&f==b)break}b||(b=f);e="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,B.subarray(a,a+Math.min(b,1024))),e=e?e+c:c,a+=1024,b-=1024;return e}return la(B,a)}
var ma="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function la(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&ma)return ma.decode(a.subarray(b,c));for(c="";;){var e=a[b++];if(!e)return c;if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;if(224==(e&240))e=(e&15)<<12|f<<6|g;else{var h=a[b++]&63;if(240==(e&248))e=(e&7)<<18|f<<12|g<<6|h;else{var m=a[b++]&63;if(248==(e&252))e=(e&3)<<24|f<<18|g<<12|h<<6|m;else{var l=a[b++]&63;e=(e&1)<<30|f<<24|g<<18|h<<12|m<<6|l}}}65536>e?c+=String.fromCharCode(e):(e-=
65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}}
function na(a,b,c,e){if(!(0<e))return 0;var f=c;e=c+e-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=e)break;b[c++]=h}else{if(2047>=h){if(c+1>=e)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=e)break;b[c++]=224|h>>12}else{if(2097151>=h){if(c+3>=e)break;b[c++]=240|h>>18}else{if(67108863>=h){if(c+4>=e)break;b[c++]=248|h>>24}else{if(c+5>=e)break;b[c++]=252|h>>30;b[c++]=128|h>>24&63}b[c++]=128|h>>18&63}b[c++]=
128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function oa(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:2097151>=e?b+4:67108863>=e?b+5:b+6}b+=1;c=pa(b);na(a,qa,c,b);return c}function ra(a,b){0<a%b&&(a+=b-a%b);return a}var buffer,qa,B,sa,C,ta,D;
function ua(){d.HEAP8=qa=new Int8Array(buffer);d.HEAP16=new Int16Array(buffer);d.HEAP32=C=new Int32Array(buffer);d.HEAPU8=B=new Uint8Array(buffer);d.HEAPU16=sa=new Uint16Array(buffer);d.HEAPU32=ta=new Uint32Array(buffer);d.HEAPF32=D=new Float32Array(buffer);d.HEAPF64=new Float64Array(buffer)}var va,E,wa,xa,ya,za,F;va=E=wa=xa=ya=za=F=0;d.reallocBuffer||(d.reallocBuffer=function(a){try{var b=qa;var c=new ArrayBuffer(a);(new Int8Array(c)).set(b)}catch(e){return!1}return Aa(c)?c:!1});var Ba;
try{Ba=Function.prototype.call.bind(Object.getOwnPropertyDescriptor(ArrayBuffer.prototype,"byteLength").get),Ba(new ArrayBuffer(4))}catch(a){Ba=function(b){return b.byteLength}}var Ca=d.TOTAL_STACK||5242880,G=d.TOTAL_MEMORY||16777216;G<Ca&&y("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+G+"! (TOTAL_STACK="+Ca+")");
d.buffer?buffer=d.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(d.wasmMemory=new WebAssembly.Memory({initial:G/65536}),buffer=d.wasmMemory.buffer):buffer=new ArrayBuffer(G),d.buffer=buffer);ua();function H(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.s;"number"===typeof c?void 0===b.c?d.dynCall_v(c):d.dynCall_vi(c,b.c):c(void 0===b.c?null:b.c)}}}var Da=[],Ea=[],Fa=[],Ga=[],Ha=[],Ia=!1;
function Ja(){var a=d.preRun.shift();Da.unshift(a)}var I=0,Ka=null,J=null;d.preloadedImages={};d.preloadedAudios={};function La(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(d.wasmBinary)return new Uint8Array(d.wasmBinary);if(d.readBinary)return d.readBinary(f);throw"both async and sync fetching of the wasm failed";}catch(t){x(t)}}function b(){return d.wasmBinary||!p&&!r||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){m=a.exports;if(m.memory){a=
m.memory;var b=d.buffer;a.byteLength<b.byteLength&&y("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);d.buffer=buffer=a;ua()}d.asm=m;d.usingWasm=!0;I--;d.monitorRunDependencies&&d.monitorRunDependencies(I);0==I&&(null!==Ka&&(clearInterval(Ka),Ka=null),J&&(a=J,J=null,a()))}function e(a){c(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,h)}).then(a,function(a){y("failed to asynchronously prepare wasm: "+
a);x(a)})}if("object"!==typeof WebAssembly)return y("no native wasm support detected"),!1;if(!(d.wasmMemory instanceof WebAssembly.Memory))return y("no native wasm Memory in use"),!1;a.memory=d.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;I++;d.monitorRunDependencies&&d.monitorRunDependencies(I);if(d.instantiateWasm)try{return d.instantiateWasm(h,c)}catch(Fb){return y("Module.instantiateWasm callback failed with error: "+Fb),!1}d.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||
La(f)||"function"!==typeof fetch?g(e):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),h).then(e,function(a){y("wasm streaming compile failed: "+a);y("falling back to ArrayBuffer instantiation");g(e)});return{}}var e="textured_cube.wast",f="textured_cube.wasm",g="textured_cube.temp.asm.js";La(e)||(e=ca(e));La(f)||(f=ca(f));La(g)||(g=ca(g));var h={global:null,env:null,asm2wasm:ka,parent:d},m=null;d.asmPreload=d.asm;var l=d.reallocBuffer;d.reallocBuffer=function(a){if("asmjs"===
q)var b=l(a);else a:{a=ra(a,d.usingWasm?65536:16777216);var c=d.buffer.byteLength;if(d.usingWasm)try{b=-1!==d.wasmMemory.grow((a-c)/65536)?d.buffer=d.wasmMemory.buffer:null;break a}catch(Tb){b=null;break a}b=void 0}return b};var q="";d.asm=function(a,b){if(!b.table){a=d.wasmTableSize;void 0===a&&(a=1024);var e=d.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==e?new WebAssembly.Table({initial:a,maximum:e,element:"anyfunc"}):new WebAssembly.Table({initial:a,
element:"anyfunc"}):Array(a);d.wasmTable=b.table}b.memoryBase||(b.memoryBase=d.STATIC_BASE);b.tableBase||(b.tableBase=0);b=c(b);assert(b,"no binaryen method succeeded.");return b}})();va=1024;E=va+6576;d.STATIC_BASE=va;d.STATIC_BUMP=6576;E+=16;var Ma=[null,[],[]],K=0;function L(){K+=4;return C[K-4>>2]}var Na={};function M(){x()}var Oa=0;
function Pa(a){return a?("number"==typeof a&&(a=A(a)),"#window"==a?window:"#document"==a?document:"#screen"==a?window.screen:"#canvas"==a?d.canvas:"string"==typeof a?document.getElementById(a):a):window}var N=null,O="",P=0,Q=null,Qa=0,Ra=0,Sa=0,Ta=0,Ua=[],Va={},Wa,Xa,R,Ya=!1,Za=!1,$a=[];
function ab(){function a(){Za=document.pointerLockElement===d.canvas||document.mozPointerLockElement===d.canvas||document.webkitPointerLockElement===d.canvas||document.msPointerLockElement===d.canvas}d.preloadPlugins||(d.preloadPlugins=[]);if(!bb){bb=!0;try{S=!0}catch(c){S=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}cb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:S?null:console.log("warning: no BlobBuilder");
db="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;d.j||"undefined"!==typeof db||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),d.j=!0);d.preloadPlugins.push({canHandle:function(a){return!d.j&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,b,f,g){var c=null;if(S)try{c=new Blob([a],{type:eb(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:eb(b)}))}catch(q){ia("Blob constructor present but fails: "+
q+"; falling back to blob builder")}c||(c=new cb,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var e=db.createObjectURL(c),l=new Image;l.onload=function(){assert(l.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=l.width;c.height=l.height;c.getContext("2d").drawImage(l,0,0);d.preloadedImages[b]=c;db.revokeObjectURL(e);f&&f(a)};l.onerror=function(){console.log("Image "+e+" could not be decoded");g&&g()};l.src=e}});d.preloadPlugins.push({canHandle:function(a){return!d.L&&
a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,f,g){function c(c){l||(l=!0,d.preloadedAudios[b]=c,f&&f(a))}function e(){l||(l=!0,d.preloadedAudios[b]=new Audio,g&&g())}var l=!1;if(S){try{var q=new Blob([a],{type:eb(b)})}catch(u){return e()}q=db.createObjectURL(q);var t=new Audio;t.addEventListener("canplaythrough",function(){c(t)},!1);t.onerror=function(){if(!l){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var e="",f=0,g=0,
h=0;h<a.length;h++)for(f=f<<8|a[h],g+=8;6<=g;){var m=f>>g-6&63;g-=6;e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[m]}2==g?(e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&3)<<4],e+="=="):4==g&&(e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&15)<<2],e+="=");t.src="data:audio/x-"+b.substr(-3)+";base64,"+e;c(t)}};t.src=q;fb(function(){c(t)})}else return e()}});var b=d.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),d.elementPointerLock&&
b.addEventListener("click",function(a){!Za&&d.canvas.requestPointerLock&&(d.canvas.requestPointerLock(),a.preventDefault())},!1))}}
function gb(a,b,c,e){if(b&&d.f&&a==d.canvas)return d.f;if(b){var f={antialias:!1,alpha:!1};if(e)for(var g in e)f[g]=e[g];if(f=hb(a,f))var h=ib[f].GLctx}else h=a.getContext("2d");if(!h)return null;c&&(b||assert("undefined"===typeof GLctx,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),d.f=h,b&&jb(f),d.M=b,$a.forEach(function(a){a()}),ab());return h}var kb=!1,lb=void 0,T=void 0;
function mb(a,b,c){function e(){Ya=!1;var a=f.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a?(f.exitFullscreen=document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){},f.exitFullscreen=f.exitFullscreen.bind(document),lb&&f.requestPointerLock(),Ya=!0,T?("undefined"!=typeof SDL&&
(C[SDL.screen>>2]=ta[SDL.screen>>2]|8388608),nb(d.canvas),ob()):nb(f)):(a.parentNode.insertBefore(f,a),a.parentNode.removeChild(a),T?("undefined"!=typeof SDL&&(C[SDL.screen>>2]=ta[SDL.screen>>2]&-8388609),nb(d.canvas),ob()):nb(f));if(d.onFullScreen)d.onFullScreen(Ya);if(d.onFullscreen)d.onFullscreen(Ya)}lb=a;T=b;pb=c;"undefined"===typeof lb&&(lb=!0);"undefined"===typeof T&&(T=!1);"undefined"===typeof pb&&(pb=null);var f=d.canvas;kb||(kb=!0,document.addEventListener("fullscreenchange",e,!1),document.addEventListener("mozfullscreenchange",
e,!1),document.addEventListener("webkitfullscreenchange",e,!1),document.addEventListener("MSFullscreenChange",e,!1));var g=document.createElement("div");f.parentNode.insertBefore(g,f);g.appendChild(f);g.requestFullscreen=g.requestFullscreen||g.mozRequestFullScreen||g.msRequestFullscreen||(g.webkitRequestFullscreen?function(){g.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(g.webkitRequestFullScreen?function(){g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);c?g.requestFullscreen({N:c}):
g.requestFullscreen()}function qb(a,b,c){y("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");qb=function(a,b,c){return mb(a,b,c)};return mb(a,b,c)}var rb=0;function sb(a){var b=Date.now();if(0===rb)rb=b+1E3/60;else for(;b+2>=rb;)rb+=1E3/60;setTimeout(a,Math.max(rb-b,0))}
function tb(a){"undefined"===typeof window?sb(a):(window.requestAnimationFrame||(window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||window.oRequestAnimationFrame||sb),window.requestAnimationFrame(a))}function fb(a){d.noExitRuntime=!0;setTimeout(function(){z||a()},1E4)}
function eb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var ub=[];function ob(){var a=d.canvas;ub.forEach(function(b){b(a.width,a.height)})}
function nb(a,b,c){b&&c?(a.C=b,a.w=c):(b=a.C,c=a.w);var e=b,f=c;d.forcedAspectRatio&&0<d.forcedAspectRatio&&(e/f<d.forcedAspectRatio?e=Math.round(f*d.forcedAspectRatio):f=Math.round(e/d.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/e,screen.height/f);e=Math.round(e*g);f=Math.round(f*g)}T?
(a.width!=e&&(a.width=e),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(e!=b||f!=c?(a.style.setProperty("width",e+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var bb,S,cb,db,pb;
function vb(a,b){Ra=a;Sa=b;if(Q)if(0==a)N=function(){var a=Math.max(0,Xa+b-M())|0;setTimeout(R,a)},O="timeout";else if(1==a)N=function(){tb(R)},O="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);r?(void 0===d.setImmediates&&(d.setImmediates=[]),d.setImmediates.push(a),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}N=function(){setImmediate(R)};O="immediate"}}
function wb(a,b,c,e,f){d.noExitRuntime=!0;assert(!Q,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Q=a;Qa=e;var g="undefined"!==typeof e?function(){d.dynCall_vi(a,e)}:function(){d.dynCall_v(a)};var h=P;R=function(){if(!z)if(0<Ua.length){var a=Date.now(),b=Ua.shift();b.s(b.c);if(Wa){var c=Wa,e=0==c%1?c-1:Math.floor(c);Wa=b.G?e:(8*c+(e+.5))/9}console.log('main loop blocker "'+
b.name+'" took '+(Date.now()-a)+" ms");d.setStatus&&(a=d.statusMessage||"Please wait...",b=Wa,c=Va.I,b?b<c?d.setStatus(a+" ("+(c-b)+"/"+c+")"):d.setStatus(a):d.setStatus(""));h<P||setTimeout(R,0)}else if(!(h<P))if(Ta=Ta+1|0,1==Ra&&1<Sa&&0!=Ta%Sa)N();else{0==Ra&&(Xa=M());"timeout"===O&&d.f&&(y("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),
O="");a:if(!(z||d.preMainLoop&&!1===d.preMainLoop())){try{g()}catch(u){if(u instanceof w)break a;u&&"object"===typeof u&&u.stack&&y("exception thrown: "+[u,u.stack]);throw u;}d.postMainLoop&&d.postMainLoop()}h<P||("object"===typeof SDL&&SDL.audio&&SDL.audio.B&&SDL.audio.B(),N())}};f||(b&&0<b?vb(0,1E3/b):vb(1,1),N());if(c)throw"SimulateInfiniteLoop";}var xb=1,yb=0,zb=[],U=[],Ab=[],V=[],W=[],ib=[],Bb=null,Cb={},Db={},Eb=[],Gb=4;function X(a){yb||(yb=a)}
function Y(a){for(var b=xb++,c=a.length;c<b;c++)a[c]=null;return b}var Hb=null,Ib=[0];
function hb(a,b){function c(){}"undefined"===typeof b.majorVersion&&"undefined"===typeof b.minorVersion&&(b.majorVersion=1,b.minorVersion=0);try{a.addEventListener("webglcontextcreationerror",c,!1);try{if(1==b.majorVersion&&0==b.minorVersion)var e=a.getContext("webgl",b)||a.getContext("experimental-webgl",b);else if(2==b.majorVersion&&0==b.minorVersion)e=a.getContext("webgl2",b);else throw"Unsupported WebGL context version "+majorVersion+"."+minorVersion+"!";}finally{a.removeEventListener("webglcontextcreationerror",
c,!1)}if(!e)throw":(";}catch(f){return 0}return e?Jb(e,b):0}function Jb(a,b){var c=Y(ib),e={handle:c,attributes:b,version:b.majorVersion,GLctx:a};a.canvas&&(a.canvas.F=e);ib[c]=e;("undefined"===typeof b.enableExtensionsByDefault||b.enableExtensionsByDefault)&&Kb(e);return c}function jb(a){a=ib[a];if(!a)return!1;GLctx=d.f=a.GLctx;Bb=a;return!0}
function Kb(a){a||(a=Bb);if(!a.A){a.A=!0;var b=a.GLctx;if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,e,f){c.drawArraysInstancedANGLE(a,b,e,f)},b.drawElementsInstanced=function(a,b,e,f,g){c.drawElementsInstancedANGLE(a,b,e,f,g)});var e=b.getExtension("OES_vertex_array_object");e&&(b.createVertexArray=function(){return e.createVertexArrayOES()},b.deleteVertexArray=function(a){e.deleteVertexArrayOES(a)},
b.bindVertexArray=function(a){e.bindVertexArrayOES(a)},b.isVertexArray=function(a){return e.isVertexArrayOES(a)});var f=b.getExtension("WEBGL_draw_buffers");f&&(b.drawBuffers=function(a,b){f.drawBuffersWEBGL(a,b)})}b.H=b.getExtension("EXT_disjoint_timer_query");var g="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=g.indexOf(a)&&b.getExtension(a)})}}var Lb,Mb;function _glDrawElements(a,b,c,e){GLctx.drawElements(a,b,c,e)}
function Nb(a,b,c,e,f){switch(b){case 6406:case 6409:case 6402:b=1;break;case 6410:b=2;break;case 6407:case 35904:b=3;break;case 6408:case 35906:b=4;break;default:return X(1280),null}switch(a){case 5121:var g=1*b;break;case 5123:case 36193:g=2*b;break;case 5125:case 5126:g=4*b;break;case 34042:g=4;break;case 33635:case 32819:case 32820:g=2;break;default:return X(1280),null}b=Gb;c*=g;b*=Math.floor((c+b-1)/b);e=0>=e?0:(e-1)*b+c;switch(a){case 5121:return B.subarray(f,f+e);case 5126:return D.subarray(f>>
2,f+e>>2);case 5125:case 34042:return ta.subarray(f>>2,f+e>>2);case 5123:case 33635:case 32819:case 32820:case 36193:return sa.subarray(f>>1,f+e>>1);default:return X(1280),null}}
aa?M=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?M=dateNow:"object"===typeof self&&self.performance&&"function"===typeof self.performance.now?M=function(){return self.performance.now()}:"object"===typeof performance&&"function"===typeof performance.now?M=function(){return performance.now()}:M=Date.now;
(function(){if("undefined"!==typeof window){window.addEventListener("gamepadconnected",function(){++Oa});window.addEventListener("gamepaddisconnected",function(){--Oa});var a=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null;a&&(Oa=a.length)}})();d.requestFullScreen=function(a,b,c){y("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");d.requestFullScreen=d.requestFullscreen;qb(a,b,c)};
d.requestFullscreen=function(a,b,c){mb(a,b,c)};d.requestAnimationFrame=function(a){tb(a)};d.setCanvasSize=function(a,b,c){nb(d.canvas,a,b);c||ob()};d.pauseMainLoop=function(){N=null;P++};d.resumeMainLoop=function(){P++;var a=Ra,b=Sa,c=Q;Q=null;wb(c,0,!1,Qa,!0);vb(a,b);N()};d.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};d.createContext=function(a,b,c,e){return gb(a,b,c,e)};var GLctx;Hb=new Float32Array(256);
for(var Z=0;256>Z;Z++)Ib[Z]=Hb.subarray(0,Z+1);for(Z=0;32>Z;Z++)Eb.push(Array(Z));var Ob=E;E=E+4+15&-16;F=Ob;wa=xa=ha(E);ya=wa+Ca;za=ha(ya);C[F>>2]=za;d.wasmTableSize=8;d.wasmMaxTableSize=8;d.m={};
d.o={abort:x,enlargeMemory:function(){var a=d.usingWasm?65536:16777216,b=2147483648-a;if(C[F>>2]>b)return!1;var c=G;for(G=Math.max(G,16777216);G<C[F>>2];)536870912>=G?G=ra(2*G,a):G=Math.min(ra((3*G+2147483648)/4,a),b);a=d.reallocBuffer(G);if(!a||a.byteLength!=G)return G=c,!1;d.buffer=buffer=a;ua();return!0},getTotalMemory:function(){return G},abortOnCannotGrowMemory:function(){x("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+G+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},
___setErrNo:function(a){d.___errno_location&&(C[d.___errno_location()>>2]=a);return a},___syscall140:function(a,b){K=b;try{var c=Na.u();L();var e=L(),f=L(),g=L();FS.K(c,e,g);C[f>>2]=c.position;c.v&&0===e&&0===g&&(c.v=null);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof FS.h||x(h),-h.i}},___syscall146:function(a,b){K=b;try{var c=L(),e=L(),f=L();for(b=a=0;b<f;b++){for(var g=C[e+8*b>>2],h=C[e+(8*b+4)>>2],m=0;m<h;m++){var l=c,q=B[g+m],t=Ma[l];assert(t);0===q||10===q?((1===l?fa:y)(la(t,
0)),t.length=0):t.push(q)}a+=h}return a}catch(u){return"undefined"!==typeof FS&&u instanceof FS.h||x(u),-u.i}},___syscall54:function(a,b){K=b;return 0},___syscall6:function(a,b){K=b;try{var c=Na.u();FS.close(c);return 0}catch(e){return"undefined"!==typeof FS&&e instanceof FS.h||x(e),-e.i}},_emscripten_get_now:M,_emscripten_memcpy_big:function(a,b,c){B.set(B.subarray(b,b+c),a);return a},_emscripten_set_canvas_element_size:function(a,b,c){a=a?Pa(a):d.canvas;if(!a)return-4;a.width=b;a.height=c;return 0},
_emscripten_set_main_loop:wb,_emscripten_webgl_create_context:function(a,b){var c={};c.alpha=!!C[b>>2];c.depth=!!C[b+4>>2];c.stencil=!!C[b+8>>2];c.antialias=!!C[b+12>>2];c.premultipliedAlpha=!!C[b+16>>2];c.preserveDrawingBuffer=!!C[b+20>>2];c.preferLowPowerToHighPerformance=!!C[b+24>>2];c.failIfMajorPerformanceCaveat=!!C[b+28>>2];c.majorVersion=C[b+32>>2];c.minorVersion=C[b+36>>2];c.enableExtensionsByDefault=C[b+40>>2];c.explicitSwapControl=C[b+44>>2];c.renderViaOffscreenBackBuffer=C[b+48>>2];a=(a=
A(a))&&"#canvas"!==a||!d.canvas?Cb[a]||Pa(a):d.canvas.id?Cb[d.canvas.id]||Pa(d.canvas.id):d.canvas;return!a||c.explicitSwapControl?0:hb(a,c)},_emscripten_webgl_init_context_attributes:function(a){C[a>>2]=1;C[a+4>>2]=1;C[a+8>>2]=0;C[a+12>>2]=1;C[a+16>>2]=1;C[a+20>>2]=0;C[a+24>>2]=0;C[a+28>>2]=0;C[a+32>>2]=1;C[a+36>>2]=0;C[a+40>>2]=1;C[a+44>>2]=0;C[a+48>>2]=0},_emscripten_webgl_make_context_current:function(a){return jb(a)?0:-5},_glActiveTexture:function(a){GLctx.activeTexture(a)},_glAttachShader:function(a,
b){GLctx.attachShader(U[a],W[b])},_glBindAttribLocation:function(a,b,c){c=A(c);GLctx.bindAttribLocation(U[a],b,c)},_glBindBuffer:function(a,b){GLctx.bindBuffer(a,b?zb[b]:null)},_glBindTexture:function(a,b){GLctx.bindTexture(a,b?Ab[b]:null)},_glBufferData:function(a,b,c,e){c?GLctx.bufferData(a,B.subarray(c,c+b),e):GLctx.bufferData(a,b,e)},_glClear:function(a){GLctx.clear(a)},_glClearColor:function(a,b,c,e){GLctx.clearColor(a,b,c,e)},_glCompileShader:function(a){GLctx.compileShader(W[a])},_glCreateProgram:function(){var a=
Y(U),b=GLctx.createProgram();b.name=a;U[a]=b;return a},_glCreateShader:function(a){var b=Y(W);W[b]=GLctx.createShader(a);return b},_glCullFace:function(a){GLctx.cullFace(a)},_glDeleteBuffers:function(a,b){for(var c=0;c<a;c++){var e=C[b+4*c>>2],f=zb[e];f&&(GLctx.deleteBuffer(f),f.name=0,zb[e]=null,e==Lb&&(Lb=0),e==Mb&&(Mb=0))}},_glDeleteShader:function(a){if(a){var b=W[a];b?(GLctx.deleteShader(b),W[a]=null):X(1281)}},_glDrawElements:_glDrawElements,_glEnable:function(a){GLctx.enable(a)},_glEnableVertexAttribArray:function(a){GLctx.enableVertexAttribArray(a)},
_glGenBuffers:function(a,b){for(var c=0;c<a;c++){var e=GLctx.createBuffer();if(!e){for(X(1282);c<a;)C[b+4*c++>>2]=0;break}var f=Y(zb);e.name=f;zb[f]=e;C[b+4*c>>2]=f}},_glGenTextures:function(a,b){for(var c=0;c<a;c++){var e=GLctx.createTexture();if(!e){for(X(1282);c<a;)C[b+4*c++>>2]=0;break}var f=Y(Ab);e.name=f;Ab[f]=e;C[b+4*c>>2]=f}},_glGetProgramiv:function(a,b,c){if(c)if(a>=xb)X(1281);else{var e=Db[a];if(e)if(35716==b)a=GLctx.getProgramInfoLog(U[a]),null===a&&(a="(unknown error)"),C[c>>2]=a.length+
1;else if(35719==b)C[c>>2]=e.g;else if(35722==b){if(-1==e.a){a=U[a];var f=GLctx.getProgramParameter(a,GLctx.ACTIVE_ATTRIBUTES);for(b=e.a=0;b<f;++b)e.a=Math.max(e.a,GLctx.getActiveAttrib(a,b).name.length+1)}C[c>>2]=e.a}else if(35381==b){if(-1==e.b)for(a=U[a],f=GLctx.getProgramParameter(a,GLctx.D),b=e.b=0;b<f;++b){var g=GLctx.J(a,b);e.b=Math.max(e.b,g.length+1)}C[c>>2]=e.b}else C[c>>2]=GLctx.getProgramParameter(U[a],b);else X(1282)}else X(1281)},_glGetShaderInfoLog:function(a,b,c,e){a=GLctx.getShaderInfoLog(W[a]);
null===a&&(a="(unknown error)");0<b&&e?(b=na(a,B,e,b),c&&(C[c>>2]=b)):c&&(C[c>>2]=0)},_glGetShaderiv:function(a,b,c){c?35716==b?(a=GLctx.getShaderInfoLog(W[a]),null===a&&(a="(unknown error)"),C[c>>2]=a.length+1):35720==b?(a=GLctx.getShaderSource(W[a]),C[c>>2]=null===a||0==a.length?0:a.length+1):C[c>>2]=GLctx.getShaderParameter(W[a],b):X(1281)},_glGetUniformLocation:function(a,b){b=A(b);var c=0;if(-1!==b.indexOf("]",b.length-1)){var e=b.lastIndexOf("["),f=b.slice(e+1,-1);if(0<f.length&&(c=parseInt(f),
0>c))return-1;b=b.slice(0,e)}a=Db[a];return a?(b=a.l[b])&&c<b[0]?b[1]+c:-1:-1},_glLinkProgram:function(a){GLctx.linkProgram(U[a]);Db[a]=null;var b=U[a];Db[a]={l:{},g:0,a:-1,b:-1};a=Db[a];for(var c=a.l,e=GLctx.getProgramParameter(b,GLctx.ACTIVE_UNIFORMS),f=0;f<e;++f){var g=GLctx.getActiveUniform(b,f),h=g.name;a.g=Math.max(a.g,h.length+1);-1!==h.indexOf("]",h.length-1)&&(h=h.slice(0,h.lastIndexOf("[")));var m=GLctx.getUniformLocation(b,h);if(null!=m){var l=Y(V);c[h]=[g.size,l];V[l]=m;for(var q=1;q<
g.size;++q)m=GLctx.getUniformLocation(b,h+"["+q+"]"),l=Y(V),V[l]=m}}},_glPixelStorei:function(a,b){3333==a||3317==a&&(Gb=b);GLctx.pixelStorei(a,b)},_glShaderSource:function(a,b,c,e){for(var f="",g=0;g<b;++g){if(e){var h=C[e+4*g>>2];h=0>h?A(C[c+4*g>>2]):A(C[c+4*g>>2],h)}else h=A(C[c+4*g>>2]);f+=h}GLctx.shaderSource(W[a],f)},_glTexImage2D:function(a,b,c,e,f,g,h,m,l){var q=null;l&&(q=Nb(m,h,e,f,l));GLctx.texImage2D(a,b,c,e,f,g,h,m,q)},_glTexParameteri:function(a,b,c){GLctx.texParameteri(a,b,c)},_glUniform1i:function(a,
b){GLctx.uniform1i(V[a],b)},_glUniformMatrix4fv:function(a,b,c,e){if(256>=16*b){var f=Ib[16*b-1];for(var g=0;g<16*b;g+=16)f[g]=D[e+4*g>>2],f[g+1]=D[e+(4*g+4)>>2],f[g+2]=D[e+(4*g+8)>>2],f[g+3]=D[e+(4*g+12)>>2],f[g+4]=D[e+(4*g+16)>>2],f[g+5]=D[e+(4*g+20)>>2],f[g+6]=D[e+(4*g+24)>>2],f[g+7]=D[e+(4*g+28)>>2],f[g+8]=D[e+(4*g+32)>>2],f[g+9]=D[e+(4*g+36)>>2],f[g+10]=D[e+(4*g+40)>>2],f[g+11]=D[e+(4*g+44)>>2],f[g+12]=D[e+(4*g+48)>>2],f[g+13]=D[e+(4*g+52)>>2],f[g+14]=D[e+(4*g+56)>>2],f[g+15]=D[e+(4*g+60)>>2]}else f=
D.subarray(e>>2,e+64*b>>2);GLctx.uniformMatrix4fv(V[a],!!c,f)},_glUseProgram:function(a){GLctx.useProgram(a?U[a]:null)},_glValidateProgram:function(a){GLctx.validateProgram(U[a])},_glVertexAttribPointer:function(a,b,c,e,f,g){GLctx.vertexAttribPointer(a,b,c,!!e,f,g)},DYNAMICTOP_PTR:F,STACKTOP:xa};var Pb=d.asm(d.m,d.o,buffer);d.asm=Pb;d.___errno_location=function(){return d.asm.___errno_location.apply(null,arguments)};
var Aa=d._emscripten_replace_memory=function(){return d.asm._emscripten_replace_memory.apply(null,arguments)};d._main=function(){return d.asm._main.apply(null,arguments)};d._malloc=function(){return d.asm._malloc.apply(null,arguments)};var pa=d.stackAlloc=function(){return d.asm.stackAlloc.apply(null,arguments)};d.dynCall_iiii=function(){return d.asm.dynCall_iiii.apply(null,arguments)};d.dynCall_v=function(){return d.asm.dynCall_v.apply(null,arguments)};d.asm=Pb;
function w(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}w.prototype=Error();w.prototype.constructor=w;J=function Qb(){d.calledRun||Rb();d.calledRun||(J=Qb)};
d.callMain=function(a){a=a||[];Ia||(Ia=!0,H(Ea));var b=a.length+1,c=pa(4*(b+1));C[c>>2]=oa(d.thisProgram);for(var e=1;e<b;e++)C[(c>>2)+e]=oa(a[e-1]);C[(c>>2)+b]=0;try{var f=d._main(b,c,0);if(!d.noExitRuntime||0!==f){if(!d.noExitRuntime&&(z=!0,xa=void 0,H(Ga),d.onExit))d.onExit(f);d.quit(f,new w(f))}}catch(g){g instanceof w||("SimulateInfiniteLoop"==g?d.noExitRuntime=!0:((a=g)&&"object"===typeof g&&g.stack&&(a=[g,g.stack]),y("exception thrown: "+a),d.quit(1,g)))}finally{}};
function Rb(a){function b(){if(!d.calledRun&&(d.calledRun=!0,!z)){Ia||(Ia=!0,H(Ea));H(Fa);if(d.onRuntimeInitialized)d.onRuntimeInitialized();d._main&&Sb&&d.callMain(a);if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var b=d.postRun.shift();Ha.unshift(b)}H(Ha)}}a=a||d.arguments;if(!(0<I)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)Ja();H(Da);0<I||d.calledRun||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},
1);b()},1)):b())}}d.run=Rb;function x(a){if(d.onAbort)d.onAbort(a);void 0!==a?(fa(a),y(a),a=JSON.stringify(a)):a="";z=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}d.abort=x;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();var Sb=!0;d.noInitialRun&&(Sb=!1);d.noExitRuntime=!0;Rb();
