var d;d||(d=typeof Module !== 'undefined' ? Module : {});var k={},m;for(m in d)d.hasOwnProperty(m)&&(k[m]=d[m]);d.arguments=[];d.thisProgram="./this.program";d.quit=function(a,b){throw b;};d.preRun=[];d.postRun=[];var p=!1,u=!1,aa=!1,ba=!1;p="object"===typeof window;u="function"===typeof importScripts;aa="object"===typeof process&&"function"===typeof require&&!p&&!u;ba=!p&&!aa&&!u;var v="";function ca(a){return d.locateFile?d.locateFile(a,v):v+a}
if(aa){v=__dirname+"/";var da,ea;d.read=function(a,b){da||(da=require("fs"));ea||(ea=require("path"));a=ea.normalize(a);a=da.readFileSync(a);return b?a:a.toString()};d.readBinary=function(a){a=d.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(d.thisProgram=process.argv[1].replace(/\\/g,"/"));d.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=d);process.on("uncaughtException",function(a){if(!(a instanceof w))throw a;});process.on("unhandledRejection",
x);d.quit=function(a){process.exit(a)};d.inspect=function(){return"[Emscripten Module object]"}}else if(ba)"undefined"!=typeof read&&(d.read=function(a){return read(a)}),d.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?d.arguments=scriptArgs:"undefined"!=typeof arguments&&(d.arguments=arguments),"function"===typeof quit&&(d.quit=function(a){quit(a)});else if(p||u)u?
v=self.location.href:document.currentScript&&(v=document.currentScript.src),v=0!==v.indexOf("blob:")?v.substr(0,v.lastIndexOf("/")+1):"",d.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(d.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),d.readAsync=function(a,b,c){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==
e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)},d.setWindowTitle=function(a){document.title=a};var fa=d.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),y=d.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||fa);for(m in k)k.hasOwnProperty(m)&&(d[m]=k[m]);k=void 0;function ha(a){var b;b||(b=16);return Math.ceil(a/b)*b}
function ia(a){ja||(ja={});ja[a]||(ja[a]=1,y(a))}var ja,ka={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},z=!1;function assert(a,b){a||x("Assertion failed: "+b)}function A(a,b){if(0===b||!a)return"";for(var c=0,e,f=0;;){e=B[a+f>>0];c|=e;if(0==e&&!b)break;f++;if(b&&f==b)break}b||(b=f);e="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,B.subarray(a,a+Math.min(b,1024))),e=e?e+c:c,a+=1024,b-=1024;return e}return la(B,a)}
var ma="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function la(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&ma)return ma.decode(a.subarray(b,c));for(c="";;){var e=a[b++];if(!e)return c;if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;if(224==(e&240))e=(e&15)<<12|f<<6|g;else{var h=a[b++]&63;if(240==(e&248))e=(e&7)<<18|f<<12|g<<6|h;else{var n=a[b++]&63;if(248==(e&252))e=(e&3)<<24|f<<18|g<<12|h<<6|n;else{var l=a[b++]&63;e=(e&1)<<30|f<<24|g<<18|h<<12|n<<6|l}}}65536>e?c+=String.fromCharCode(e):(e-=
65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}}
function na(a,b,c,e){if(!(0<e))return 0;var f=c;e=c+e-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var n=a.charCodeAt(++g);h=65536+((h&1023)<<10)|n&1023}if(127>=h){if(c>=e)break;b[c++]=h}else{if(2047>=h){if(c+1>=e)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=e)break;b[c++]=224|h>>12}else{if(2097151>=h){if(c+3>=e)break;b[c++]=240|h>>18}else{if(67108863>=h){if(c+4>=e)break;b[c++]=248|h>>24}else{if(c+5>=e)break;b[c++]=252|h>>30;b[c++]=128|h>>24&63}b[c++]=128|h>>18&63}b[c++]=
128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function oa(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:2097151>=e?b+4:67108863>=e?b+5:b+6}b+=1;c=pa(b);na(a,qa,c,b);return c}var buffer,qa,B,C,ra,D;
function sa(){d.HEAP8=qa=new Int8Array(buffer);d.HEAP16=new Int16Array(buffer);d.HEAP32=C=new Int32Array(buffer);d.HEAPU8=B=new Uint8Array(buffer);d.HEAPU16=new Uint16Array(buffer);d.HEAPU32=ra=new Uint32Array(buffer);d.HEAPF32=D=new Float32Array(buffer);d.HEAPF64=new Float64Array(buffer)}var ta,E,ua,va,wa,xa,ya;ta=E=ua=va=wa=xa=ya=0;
function za(){x("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+F+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var Aa=d.TOTAL_STACK||5242880,F=d.TOTAL_MEMORY||16777216;F<Aa&&y("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+F+"! (TOTAL_STACK="+Aa+")");
d.buffer?buffer=d.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(d.wasmMemory=new WebAssembly.Memory({initial:F/65536,maximum:F/65536}),buffer=d.wasmMemory.buffer):buffer=new ArrayBuffer(F),d.buffer=buffer);sa();function G(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.s;"number"===typeof c?void 0===b.c?d.dynCall_v(c):d.dynCall_vi(c,b.c):c(void 0===b.c?null:b.c)}}}var Ba=[],Ca=[],Da=[],Ea=[],Fa=[],Ga=!1;
function Ha(){var a=d.preRun.shift();Ba.unshift(a)}var H=0,Ia=null,I=null;d.preloadedImages={};d.preloadedAudios={};function Ja(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(d.wasmBinary)return new Uint8Array(d.wasmBinary);if(d.readBinary)return d.readBinary(f);throw"both async and sync fetching of the wasm failed";}catch(r){x(r)}}function b(){return d.wasmBinary||!p&&!u||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){n=a.exports;if(n.memory){a=
n.memory;var b=d.buffer;a.byteLength<b.byteLength&&y("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);d.buffer=buffer=a;sa()}d.asm=n;d.usingWasm=!0;H--;d.monitorRunDependencies&&d.monitorRunDependencies(H);0==H&&(null!==Ia&&(clearInterval(Ia),Ia=null),I&&(a=I,I=null,a()))}function e(a){c(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,h)}).then(a,function(a){y("failed to asynchronously prepare wasm: "+
a);x(a)})}if("object"!==typeof WebAssembly)return y("no native wasm support detected"),!1;if(!(d.wasmMemory instanceof WebAssembly.Memory))return y("no native wasm Memory in use"),!1;a.memory=d.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;H++;d.monitorRunDependencies&&d.monitorRunDependencies(H);if(d.instantiateWasm)try{return d.instantiateWasm(h,c)}catch(Ab){return y("Module.instantiateWasm callback failed with error: "+Ab),!1}d.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||
Ja(f)||"function"!==typeof fetch?g(e):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),h).then(e,function(a){y("wasm streaming compile failed: "+a);y("falling back to ArrayBuffer instantiation");g(e)});return{}}var e="indexed_plane.wast",f="indexed_plane.wasm",g="indexed_plane.temp.asm.js";Ja(e)||(e=ca(e));Ja(f)||(f=ca(f));Ja(g)||(g=ca(g));var h={global:null,env:null,asm2wasm:ka,parent:d},n=null;d.asmPreload=d.asm;var l=d.reallocBuffer;d.reallocBuffer=function(a){if("asmjs"===
q)var b=l(a);else a:{var c=d.usingWasm?65536:16777216;0<a%c&&(a+=c-a%c);c=d.buffer.byteLength;if(d.usingWasm)try{b=-1!==d.wasmMemory.grow((a-c)/65536)?d.buffer=d.wasmMemory.buffer:null;break a}catch(Nb){b=null;break a}b=void 0}return b};var q="";d.asm=function(a,b){if(!b.table){a=d.wasmTableSize;void 0===a&&(a=1024);var e=d.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==e?new WebAssembly.Table({initial:a,maximum:e,element:"anyfunc"}):new WebAssembly.Table({initial:a,
element:"anyfunc"}):Array(a);d.wasmTable=b.table}b.memoryBase||(b.memoryBase=d.STATIC_BASE);b.tableBase||(b.tableBase=0);b=c(b);assert(b,"no binaryen method succeeded.");return b}})();ta=1024;E=ta+6288;d.STATIC_BASE=ta;d.STATIC_BUMP=6288;E+=16;var Ka=[null,[],[]],J=0;function K(){J+=4;return C[J-4>>2]}var La={};function L(){x()}var Ma=0;
function Na(a){return a?("number"==typeof a&&(a=A(a)),"#window"==a?window:"#document"==a?document:"#screen"==a?window.screen:"#canvas"==a?d.canvas:"string"==typeof a?document.getElementById(a):a):window}var M=null,N="",O=0,P=null,Oa=0,Pa=0,Qa=0,Ra=0,Sa=[],Ta={},Ua,Va,Q,Wa=!1,Xa=!1,Ya=[];
function Za(){function a(){Xa=document.pointerLockElement===d.canvas||document.mozPointerLockElement===d.canvas||document.webkitPointerLockElement===d.canvas||document.msPointerLockElement===d.canvas}d.preloadPlugins||(d.preloadPlugins=[]);if(!$a){$a=!0;try{R=!0}catch(c){R=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}ab="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:R?null:console.log("warning: no BlobBuilder");
S="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;d.j||"undefined"!==typeof S||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),d.j=!0);d.preloadPlugins.push({canHandle:function(a){return!d.j&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,b,f,g){var c=null;if(R)try{c=new Blob([a],{type:bb(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:bb(b)}))}catch(q){ia("Blob constructor present but fails: "+
q+"; falling back to blob builder")}c||(c=new ab,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var e=S.createObjectURL(c),l=new Image;l.onload=function(){assert(l.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=l.width;c.height=l.height;c.getContext("2d").drawImage(l,0,0);d.preloadedImages[b]=c;S.revokeObjectURL(e);f&&f(a)};l.onerror=function(){console.log("Image "+e+" could not be decoded");g&&g()};l.src=e}});d.preloadPlugins.push({canHandle:function(a){return!d.L&&
a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,f,g){function c(c){l||(l=!0,d.preloadedAudios[b]=c,f&&f(a))}function e(){l||(l=!0,d.preloadedAudios[b]=new Audio,g&&g())}var l=!1;if(R){try{var q=new Blob([a],{type:bb(b)})}catch(t){return e()}q=S.createObjectURL(q);var r=new Audio;r.addEventListener("canplaythrough",function(){c(r)},!1);r.onerror=function(){if(!l){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var e="",f=0,g=0,h=
0;h<a.length;h++)for(f=f<<8|a[h],g+=8;6<=g;){var n=f>>g-6&63;g-=6;e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[n]}2==g?(e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&3)<<4],e+="=="):4==g&&(e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&15)<<2],e+="=");r.src="data:audio/x-"+b.substr(-3)+";base64,"+e;c(r)}};r.src=q;cb(function(){c(r)})}else return e()}});var b=d.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),d.elementPointerLock&&
b.addEventListener("click",function(a){!Xa&&d.canvas.requestPointerLock&&(d.canvas.requestPointerLock(),a.preventDefault())},!1))}}
function db(a,b,c,e){if(b&&d.f&&a==d.canvas)return d.f;if(b){var f={antialias:!1,alpha:!1};if(e)for(var g in e)f[g]=e[g];if(f=eb(a,f))var h=fb[f].GLctx}else h=a.getContext("2d");if(!h)return null;c&&(b||assert("undefined"===typeof GLctx,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),d.f=h,b&&gb(f),d.M=b,Ya.forEach(function(a){a()}),Za());return h}var hb=!1,ib=void 0,T=void 0;
function jb(a,b,c){function e(){Wa=!1;var a=f.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a?(f.exitFullscreen=document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){},f.exitFullscreen=f.exitFullscreen.bind(document),ib&&f.requestPointerLock(),Wa=!0,T?("undefined"!=typeof SDL&&
(C[SDL.screen>>2]=ra[SDL.screen>>2]|8388608),kb(d.canvas),lb()):kb(f)):(a.parentNode.insertBefore(f,a),a.parentNode.removeChild(a),T?("undefined"!=typeof SDL&&(C[SDL.screen>>2]=ra[SDL.screen>>2]&-8388609),kb(d.canvas),lb()):kb(f));if(d.onFullScreen)d.onFullScreen(Wa);if(d.onFullscreen)d.onFullscreen(Wa)}ib=a;T=b;mb=c;"undefined"===typeof ib&&(ib=!0);"undefined"===typeof T&&(T=!1);"undefined"===typeof mb&&(mb=null);var f=d.canvas;hb||(hb=!0,document.addEventListener("fullscreenchange",e,!1),document.addEventListener("mozfullscreenchange",
e,!1),document.addEventListener("webkitfullscreenchange",e,!1),document.addEventListener("MSFullscreenChange",e,!1));var g=document.createElement("div");f.parentNode.insertBefore(g,f);g.appendChild(f);g.requestFullscreen=g.requestFullscreen||g.mozRequestFullScreen||g.msRequestFullscreen||(g.webkitRequestFullscreen?function(){g.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(g.webkitRequestFullScreen?function(){g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);c?g.requestFullscreen({N:c}):
g.requestFullscreen()}function nb(a,b,c){y("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");nb=function(a,b,c){return jb(a,b,c)};return jb(a,b,c)}var ob=0;function pb(a){var b=Date.now();if(0===ob)ob=b+1E3/60;else for(;b+2>=ob;)ob+=1E3/60;setTimeout(a,Math.max(ob-b,0))}
function qb(a){"undefined"===typeof window?pb(a):(window.requestAnimationFrame||(window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||window.oRequestAnimationFrame||pb),window.requestAnimationFrame(a))}function cb(a){d.noExitRuntime=!0;setTimeout(function(){z||a()},1E4)}
function bb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var rb=[];function lb(){var a=d.canvas;rb.forEach(function(b){b(a.width,a.height)})}
function kb(a,b,c){b&&c?(a.C=b,a.w=c):(b=a.C,c=a.w);var e=b,f=c;d.forcedAspectRatio&&0<d.forcedAspectRatio&&(e/f<d.forcedAspectRatio?e=Math.round(f*d.forcedAspectRatio):f=Math.round(e/d.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/e,screen.height/f);e=Math.round(e*g);f=Math.round(f*g)}T?
(a.width!=e&&(a.width=e),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(e!=b||f!=c?(a.style.setProperty("width",e+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var $a,R,ab,S,mb;
function sb(a,b){Pa=a;Qa=b;if(P)if(0==a)M=function(){var a=Math.max(0,Va+b-L())|0;setTimeout(Q,a)},N="timeout";else if(1==a)M=function(){qb(Q)},N="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);u?(void 0===d.setImmediates&&(d.setImmediates=[]),d.setImmediates.push(a),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}M=function(){setImmediate(Q)};N="immediate"}}
function tb(a,b,c,e,f){d.noExitRuntime=!0;assert(!P,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");P=a;Oa=e;var g="undefined"!==typeof e?function(){d.dynCall_vi(a,e)}:function(){d.dynCall_v(a)};var h=O;Q=function(){if(!z)if(0<Sa.length){var a=Date.now(),b=Sa.shift();b.s(b.c);if(Ua){var c=Ua,e=0==c%1?c-1:Math.floor(c);Ua=b.G?e:(8*c+(e+.5))/9}console.log('main loop blocker "'+
b.name+'" took '+(Date.now()-a)+" ms");d.setStatus&&(a=d.statusMessage||"Please wait...",b=Ua,c=Ta.I,b?b<c?d.setStatus(a+" ("+(c-b)+"/"+c+")"):d.setStatus(a):d.setStatus(""));h<O||setTimeout(Q,0)}else if(!(h<O))if(Ra=Ra+1|0,1==Pa&&1<Qa&&0!=Ra%Qa)M();else{0==Pa&&(Va=L());"timeout"===N&&d.f&&(y("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),
N="");a:if(!(z||d.preMainLoop&&!1===d.preMainLoop())){try{g()}catch(t){if(t instanceof w)break a;t&&"object"===typeof t&&t.stack&&y("exception thrown: "+[t,t.stack]);throw t;}d.postMainLoop&&d.postMainLoop()}h<O||("object"===typeof SDL&&SDL.audio&&SDL.audio.B&&SDL.audio.B(),M())}};f||(b&&0<b?sb(0,1E3/b):sb(1,1),M());if(c)throw"SimulateInfiniteLoop";}var ub=1,vb=0,wb=[],U=[],V=[],W=[],fb=[],xb=null,yb={},zb={},Bb=[];function X(a){vb||(vb=a)}
function Y(a){for(var b=ub++,c=a.length;c<b;c++)a[c]=null;return b}var Cb=null,Db=[0];
function eb(a,b){function c(){}"undefined"===typeof b.majorVersion&&"undefined"===typeof b.minorVersion&&(b.majorVersion=1,b.minorVersion=0);try{a.addEventListener("webglcontextcreationerror",c,!1);try{if(1==b.majorVersion&&0==b.minorVersion)var e=a.getContext("webgl",b)||a.getContext("experimental-webgl",b);else if(2==b.majorVersion&&0==b.minorVersion)e=a.getContext("webgl2",b);else throw"Unsupported WebGL context version "+majorVersion+"."+minorVersion+"!";}finally{a.removeEventListener("webglcontextcreationerror",
c,!1)}if(!e)throw":(";}catch(f){return 0}return e?Eb(e,b):0}function Eb(a,b){var c=Y(fb),e={handle:c,attributes:b,version:b.majorVersion,GLctx:a};a.canvas&&(a.canvas.F=e);fb[c]=e;("undefined"===typeof b.enableExtensionsByDefault||b.enableExtensionsByDefault)&&Fb(e);return c}function gb(a){a=fb[a];if(!a)return!1;GLctx=d.f=a.GLctx;xb=a;return!0}
function Fb(a){a||(a=xb);if(!a.A){a.A=!0;var b=a.GLctx;if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,e,f){c.drawArraysInstancedANGLE(a,b,e,f)},b.drawElementsInstanced=function(a,b,e,f,g){c.drawElementsInstancedANGLE(a,b,e,f,g)});var e=b.getExtension("OES_vertex_array_object");e&&(b.createVertexArray=function(){return e.createVertexArrayOES()},b.deleteVertexArray=function(a){e.deleteVertexArrayOES(a)},
b.bindVertexArray=function(a){e.bindVertexArrayOES(a)},b.isVertexArray=function(a){return e.isVertexArrayOES(a)});var f=b.getExtension("WEBGL_draw_buffers");f&&(b.drawBuffers=function(a,b){f.drawBuffersWEBGL(a,b)})}b.H=b.getExtension("EXT_disjoint_timer_query");var g="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=g.indexOf(a)&&b.getExtension(a)})}}var Gb,Hb;function _glDrawElements(a,b,c,e){GLctx.drawElements(a,b,c,e)}
aa?L=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?L=dateNow:"object"===typeof self&&self.performance&&"function"===typeof self.performance.now?L=function(){return self.performance.now()}:"object"===typeof performance&&"function"===typeof performance.now?L=function(){return performance.now()}:L=Date.now;
(function(){if("undefined"!==typeof window){window.addEventListener("gamepadconnected",function(){++Ma});window.addEventListener("gamepaddisconnected",function(){--Ma});var a=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null;a&&(Ma=a.length)}})();d.requestFullScreen=function(a,b,c){y("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");d.requestFullScreen=d.requestFullscreen;nb(a,b,c)};
d.requestFullscreen=function(a,b,c){jb(a,b,c)};d.requestAnimationFrame=function(a){qb(a)};d.setCanvasSize=function(a,b,c){kb(d.canvas,a,b);c||lb()};d.pauseMainLoop=function(){M=null;O++};d.resumeMainLoop=function(){O++;var a=Pa,b=Qa,c=P;P=null;tb(c,0,!1,Oa,!0);sb(a,b);M()};d.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};d.createContext=function(a,b,c,e){return db(a,b,c,e)};var GLctx;Cb=new Float32Array(256);
for(var Z=0;256>Z;Z++)Db[Z]=Cb.subarray(0,Z+1);for(Z=0;32>Z;Z++)Bb.push(Array(Z));var Ib=E;E=E+4+15&-16;ya=Ib;ua=va=ha(E);wa=ua+Aa;xa=ha(wa);C[ya>>2]=xa;d.wasmTableSize=8;d.wasmMaxTableSize=8;d.m={};
d.o={abort:x,enlargeMemory:function(){za()},getTotalMemory:function(){return F},abortOnCannotGrowMemory:za,___setErrNo:function(a){d.___errno_location&&(C[d.___errno_location()>>2]=a);return a},___syscall140:function(a,b){J=b;try{var c=La.u();K();var e=K(),f=K(),g=K();FS.K(c,e,g);C[f>>2]=c.position;c.v&&0===e&&0===g&&(c.v=null);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof FS.h||x(h),-h.i}},___syscall146:function(a,b){J=b;try{var c=K(),e=K(),f=K();for(b=a=0;b<f;b++){for(var g=C[e+
8*b>>2],h=C[e+(8*b+4)>>2],n=0;n<h;n++){var l=c,q=B[g+n],r=Ka[l];assert(r);0===q||10===q?((1===l?fa:y)(la(r,0)),r.length=0):r.push(q)}a+=h}return a}catch(t){return"undefined"!==typeof FS&&t instanceof FS.h||x(t),-t.i}},___syscall54:function(a,b){J=b;return 0},___syscall6:function(a,b){J=b;try{var c=La.u();FS.close(c);return 0}catch(e){return"undefined"!==typeof FS&&e instanceof FS.h||x(e),-e.i}},_emscripten_get_now:L,_emscripten_memcpy_big:function(a,b,c){B.set(B.subarray(b,b+c),a);return a},_emscripten_set_canvas_element_size:function(a,
b,c){a=a?Na(a):d.canvas;if(!a)return-4;a.width=b;a.height=c;return 0},_emscripten_set_main_loop:tb,_emscripten_webgl_create_context:function(a,b){var c={};c.alpha=!!C[b>>2];c.depth=!!C[b+4>>2];c.stencil=!!C[b+8>>2];c.antialias=!!C[b+12>>2];c.premultipliedAlpha=!!C[b+16>>2];c.preserveDrawingBuffer=!!C[b+20>>2];c.preferLowPowerToHighPerformance=!!C[b+24>>2];c.failIfMajorPerformanceCaveat=!!C[b+28>>2];c.majorVersion=C[b+32>>2];c.minorVersion=C[b+36>>2];c.enableExtensionsByDefault=C[b+40>>2];c.explicitSwapControl=
C[b+44>>2];c.renderViaOffscreenBackBuffer=C[b+48>>2];a=(a=A(a))&&"#canvas"!==a||!d.canvas?yb[a]||Na(a):d.canvas.id?yb[d.canvas.id]||Na(d.canvas.id):d.canvas;return!a||c.explicitSwapControl?0:eb(a,c)},_emscripten_webgl_init_context_attributes:function(a){C[a>>2]=1;C[a+4>>2]=1;C[a+8>>2]=0;C[a+12>>2]=1;C[a+16>>2]=1;C[a+20>>2]=0;C[a+24>>2]=0;C[a+28>>2]=0;C[a+32>>2]=1;C[a+36>>2]=0;C[a+40>>2]=1;C[a+44>>2]=0;C[a+48>>2]=0},_emscripten_webgl_make_context_current:function(a){return gb(a)?0:-5},_glAttachShader:function(a,
b){GLctx.attachShader(U[a],W[b])},_glBindAttribLocation:function(a,b,c){c=A(c);GLctx.bindAttribLocation(U[a],b,c)},_glBindBuffer:function(a,b){GLctx.bindBuffer(a,b?wb[b]:null)},_glBufferData:function(a,b,c,e){c?GLctx.bufferData(a,B.subarray(c,c+b),e):GLctx.bufferData(a,b,e)},_glClear:function(a){GLctx.clear(a)},_glClearColor:function(a,b,c,e){GLctx.clearColor(a,b,c,e)},_glCompileShader:function(a){GLctx.compileShader(W[a])},_glCreateProgram:function(){var a=Y(U),b=GLctx.createProgram();b.name=a;U[a]=
b;return a},_glCreateShader:function(a){var b=Y(W);W[b]=GLctx.createShader(a);return b},_glCullFace:function(a){GLctx.cullFace(a)},_glDeleteBuffers:function(a,b){for(var c=0;c<a;c++){var e=C[b+4*c>>2],f=wb[e];f&&(GLctx.deleteBuffer(f),f.name=0,wb[e]=null,e==Gb&&(Gb=0),e==Hb&&(Hb=0))}},_glDeleteShader:function(a){if(a){var b=W[a];b?(GLctx.deleteShader(b),W[a]=null):X(1281)}},_glDepthFunc:function(a){GLctx.depthFunc(a)},_glDrawElements:_glDrawElements,_glEnableVertexAttribArray:function(a){GLctx.enableVertexAttribArray(a)},
_glGenBuffers:function(a,b){for(var c=0;c<a;c++){var e=GLctx.createBuffer();if(!e){for(X(1282);c<a;)C[b+4*c++>>2]=0;break}var f=Y(wb);e.name=f;wb[f]=e;C[b+4*c>>2]=f}},_glGetProgramiv:function(a,b,c){if(c)if(a>=ub)X(1281);else{var e=zb[a];if(e)if(35716==b)a=GLctx.getProgramInfoLog(U[a]),null===a&&(a="(unknown error)"),C[c>>2]=a.length+1;else if(35719==b)C[c>>2]=e.g;else if(35722==b){if(-1==e.a){a=U[a];var f=GLctx.getProgramParameter(a,GLctx.ACTIVE_ATTRIBUTES);for(b=e.a=0;b<f;++b)e.a=Math.max(e.a,GLctx.getActiveAttrib(a,
b).name.length+1)}C[c>>2]=e.a}else if(35381==b){if(-1==e.b)for(a=U[a],f=GLctx.getProgramParameter(a,GLctx.D),b=e.b=0;b<f;++b){var g=GLctx.J(a,b);e.b=Math.max(e.b,g.length+1)}C[c>>2]=e.b}else C[c>>2]=GLctx.getProgramParameter(U[a],b);else X(1282)}else X(1281)},_glGetShaderInfoLog:function(a,b,c,e){a=GLctx.getShaderInfoLog(W[a]);null===a&&(a="(unknown error)");0<b&&e?(b=na(a,B,e,b),c&&(C[c>>2]=b)):c&&(C[c>>2]=0)},_glGetShaderiv:function(a,b,c){c?35716==b?(a=GLctx.getShaderInfoLog(W[a]),null===a&&(a=
"(unknown error)"),C[c>>2]=a.length+1):35720==b?(a=GLctx.getShaderSource(W[a]),C[c>>2]=null===a||0==a.length?0:a.length+1):C[c>>2]=GLctx.getShaderParameter(W[a],b):X(1281)},_glGetUniformLocation:function(a,b){b=A(b);var c=0;if(-1!==b.indexOf("]",b.length-1)){var e=b.lastIndexOf("["),f=b.slice(e+1,-1);if(0<f.length&&(c=parseInt(f),0>c))return-1;b=b.slice(0,e)}a=zb[a];return a?(b=a.l[b])&&c<b[0]?b[1]+c:-1:-1},_glLineWidth:function(a){GLctx.lineWidth(a)},_glLinkProgram:function(a){GLctx.linkProgram(U[a]);
zb[a]=null;var b=U[a];zb[a]={l:{},g:0,a:-1,b:-1};a=zb[a];for(var c=a.l,e=GLctx.getProgramParameter(b,GLctx.ACTIVE_UNIFORMS),f=0;f<e;++f){var g=GLctx.getActiveUniform(b,f),h=g.name;a.g=Math.max(a.g,h.length+1);-1!==h.indexOf("]",h.length-1)&&(h=h.slice(0,h.lastIndexOf("[")));var n=GLctx.getUniformLocation(b,h);if(null!=n){var l=Y(V);c[h]=[g.size,l];V[l]=n;for(var q=1;q<g.size;++q)n=GLctx.getUniformLocation(b,h+"["+q+"]"),l=Y(V),V[l]=n}}},_glShaderSource:function(a,b,c,e){for(var f="",g=0;g<b;++g){if(e){var h=
C[e+4*g>>2];h=0>h?A(C[c+4*g>>2]):A(C[c+4*g>>2],h)}else h=A(C[c+4*g>>2]);f+=h}GLctx.shaderSource(W[a],f)},_glUniform4fv:function(a,b,c){if(256>=4*b){var e=Db[4*b-1];for(var f=0;f<4*b;f+=4)e[f]=D[c+4*f>>2],e[f+1]=D[c+(4*f+4)>>2],e[f+2]=D[c+(4*f+8)>>2],e[f+3]=D[c+(4*f+12)>>2]}else e=D.subarray(c>>2,c+16*b>>2);GLctx.uniform4fv(V[a],e)},_glUniformMatrix4fv:function(a,b,c,e){if(256>=16*b){var f=Db[16*b-1];for(var g=0;g<16*b;g+=16)f[g]=D[e+4*g>>2],f[g+1]=D[e+(4*g+4)>>2],f[g+2]=D[e+(4*g+8)>>2],f[g+3]=D[e+
(4*g+12)>>2],f[g+4]=D[e+(4*g+16)>>2],f[g+5]=D[e+(4*g+20)>>2],f[g+6]=D[e+(4*g+24)>>2],f[g+7]=D[e+(4*g+28)>>2],f[g+8]=D[e+(4*g+32)>>2],f[g+9]=D[e+(4*g+36)>>2],f[g+10]=D[e+(4*g+40)>>2],f[g+11]=D[e+(4*g+44)>>2],f[g+12]=D[e+(4*g+48)>>2],f[g+13]=D[e+(4*g+52)>>2],f[g+14]=D[e+(4*g+56)>>2],f[g+15]=D[e+(4*g+60)>>2]}else f=D.subarray(e>>2,e+64*b>>2);GLctx.uniformMatrix4fv(V[a],!!c,f)},_glUseProgram:function(a){GLctx.useProgram(a?U[a]:null)},_glValidateProgram:function(a){GLctx.validateProgram(U[a])},_glVertexAttribPointer:function(a,
b,c,e,f,g){GLctx.vertexAttribPointer(a,b,c,!!e,f,g)},DYNAMICTOP_PTR:ya,STACKTOP:va};var Jb=d.asm(d.m,d.o,buffer);d.asm=Jb;d.___errno_location=function(){return d.asm.___errno_location.apply(null,arguments)};d._main=function(){return d.asm._main.apply(null,arguments)};d._malloc=function(){return d.asm._malloc.apply(null,arguments)};var pa=d.stackAlloc=function(){return d.asm.stackAlloc.apply(null,arguments)};d.dynCall_iiii=function(){return d.asm.dynCall_iiii.apply(null,arguments)};
d.dynCall_v=function(){return d.asm.dynCall_v.apply(null,arguments)};d.asm=Jb;function w(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}w.prototype=Error();w.prototype.constructor=w;I=function Kb(){d.calledRun||Lb();d.calledRun||(I=Kb)};
d.callMain=function(a){a=a||[];Ga||(Ga=!0,G(Ca));var b=a.length+1,c=pa(4*(b+1));C[c>>2]=oa(d.thisProgram);for(var e=1;e<b;e++)C[(c>>2)+e]=oa(a[e-1]);C[(c>>2)+b]=0;try{var f=d._main(b,c,0);if(!d.noExitRuntime||0!==f){if(!d.noExitRuntime&&(z=!0,va=void 0,G(Ea),d.onExit))d.onExit(f);d.quit(f,new w(f))}}catch(g){g instanceof w||("SimulateInfiniteLoop"==g?d.noExitRuntime=!0:((a=g)&&"object"===typeof g&&g.stack&&(a=[g,g.stack]),y("exception thrown: "+a),d.quit(1,g)))}finally{}};
function Lb(a){function b(){if(!d.calledRun&&(d.calledRun=!0,!z)){Ga||(Ga=!0,G(Ca));G(Da);if(d.onRuntimeInitialized)d.onRuntimeInitialized();d._main&&Mb&&d.callMain(a);if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var b=d.postRun.shift();Fa.unshift(b)}G(Fa)}}a=a||d.arguments;if(!(0<H)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)Ha();G(Ba);0<H||d.calledRun||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},
1);b()},1)):b())}}d.run=Lb;function x(a){if(d.onAbort)d.onAbort(a);void 0!==a?(fa(a),y(a),a=JSON.stringify(a)):a="";z=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}d.abort=x;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();var Mb=!0;d.noInitialRun&&(Mb=!1);d.noExitRuntime=!0;Lb();
